language: node_js
node_js:
 - "6.1"
install:
 - npm install
 - npm run build
script: bash ./deploy-gh-pages.sh
env:
  global:
  - GH_REF: github.com/Nanor/dnd-character-sheet.git
branches:
  only:
  - master